# Generated by Django 5.1 on 2025-09-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='goal',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount to raise if this is a cash fundraiser.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='item_name',
            field=models.CharField(blank=True, help_text='Name of the item if this is an item-based fundraiser.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per item.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='quantity_needed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
